In [1]:
from glob import glob
import pandas as pd
import numpy as np

## Get data file names

In [2]:
import os
import glob
import pandas as pd
#Path to merge
os.chdir("C:/Users/aweso/OneDrive/Documents/20210803")

In [3]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

#combine all files in the list
df = pd.concat([pd.read_csv(f) for f in all_filenames ])

all_filenames

['2-0007-20210803-125707.csv',
 '2-0007-20210803-130814.csv',
 '2-0007-20210803-133854.csv',
 '2-0007-20210803-134003.csv',
 '2-0007-20210803-134059.csv',
 '2-0007-20210803-134228.csv',
 '2-0007-20210803-134435.csv',
 '2-0007-20210803-135556.csv',
 '2-0007-20210803-135817.csv',
 '2-0007-20210803-135928.csv',
 '2-0007-20210803-140248.csv',
 '2-0007-20210803-140806.csv',
 '2-0007-20210803-140919.csv',
 '2-0007-20210803-141044.csv',
 '2-0007-20210803-141202.csv',
 '2-0007-20210803-141345.csv',
 '2-0007-20210803-141411.csv',
 '2-0007-20210803-141624.csv',
 '2-0007-20210803-141707.csv',
 '2-0007-20210803-141807.csv',
 '2-0007-20210803-141956.csv',
 '2-0007-20210803-142026.csv',
 '2-0007-20210803-142056.csv',
 '2-0007-20210803-142232.csv',
 '2-0007-20210803-142415.csv',
 '2-0007-20210803-142503.csv',
 '2-0007-20210803-142615.csv',
 '2-0007-20210803-142818.csv',
 '2-0007-20210803-143833.csv',
 '2-0007-20210803-144257.csv',
 '2-0007-20210803-144537.csv',
 '2-0007-20210803-144739.csv',
 '2-0007-20210803-144928.csv',
 '2-0007-20210803-145104.csv',
 '2-0007-20210803-145245.csv',
 '2-0007-20210803-145407.csv',
 '2-0007-20210803-145654.csv',
 '2-0007-20210803-145920.csv',
 '2-0007-20210803-150011.csv',
 '2-0007-20210803-150236.csv',
 '2-0007-20210803-150504.csv',
 '2-0007-20210803-150755.csv',
 '2-0007-20210803-151020.csv',
 '2-0007-20210803-151208.csv',
 '2-0007-20210803-151304.csv',
 '2-0007-20210803-151352.csv',
 'master.csv']

In [4]:
#export to csv
#df.to_csv( "merged.csv", index=False, encoding='utf-8-sig')
df

,#0:imgID,1:camSN,2:lat,3:lon,4:height,5:roll,6:pitch,7:heading,8:speed,9:speed_n,...,42:custLog7,43:custLog8,44:custLog9,45:unix_time_sec_fixed,46:unix_time_microsec_fixed,47:pnvgbss_field3,48:pnvgbss_field4,49:pnvgbss_field5,50:pnvgbss_field6,51:pnvgbss_field7
0,2-0007-20210803-125707-2-0007-20210803-125707-...,01932-0007,2.446821,102.685597,28.148943,0.0,0.0,183.896560,38.619,-10.704,...,,,,0,0,,,,NaN,NaN
1,2-0007-20210803-125707-2-0007-20210803-125707-...,01932-0007,2.446792,102.685595,28.104624,0.0,0.0,183.837615,38.105,-10.562,...,,,,0,0,,,,NaN,NaN
2,2-0007-20210803-125707-2-0007-20210803-125707-...,01932-0007,2.446764,102.685593,28.069963,0.0,0.0,183.822042,37.999,-10.523,...,,,,0,0,,,,NaN,NaN
3,2-0007-20210803-125707-2-0007-20210803-125707-...,01932-0007,2.446735,102.685591,28.067659,0.0,0.0,183.837356,37.910,-10.503,...,,,,0,0,,,,NaN,NaN
4,2-0007-20210803-125707-2-0007-20210803-125707-...,01932-0007,2.446707,102.685590,28.068172,0.0,0.0,183.834719,37.751,-10.462,...,,,,0,0,,,,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7156,2-0007-20210803-151352-000000075,01932-0007,2.441387,102.687680,29.541334,0.0,0.0,184.555140,22.563,-6.242,...,,,,0,0,,,,NaN,NaN
7157,2-0007-20210803-151352-000000076,01932-0007,2.441358,102.687678,29.551847,0.0,0.0,184.850068,22.293,-6.173,...,,,,0,0,,,,NaN,NaN
7158,2-0007-20210803-151352-000000077,01932-0007,2.441331,102.687676,29.610357,0.0,0.0,185.201085,21.869,-6.055,...,,,,0,0,,,,NaN,NaN
7159,2-0007-20210803-151352-000000078,01932-0007,2.441304,102.687673,29.642067,0.0,0.0,185.479538,21.361,-5.909,...,,,,0,0,,,,NaN,NaN
7160,2-0007-20210803-151352-000000079,01932-0007,2.441275,102.687670,29.685030,0.0,0.0,185.394953,21.027,-5.838,...,,,,0,0,,,,NaN,NaN

## Drop columns

In [5]:
#Drop columns 
df.drop(df.columns[[1,8,9,10,11,15,16,17,18,19,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51]], axis=1, inplace=True)
df.head()

,#0:imgID,2:lat,3:lon,4:height,5:roll,6:pitch,7:heading,12:date,13:time,14:unix_time_sec,20:distancetoprevious
0,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446821,102.685597,28.148943,0.0,0.0,183.896560,2021-08-03,04:57:56.000180,1627966676,0.0
1,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446792,102.685595,28.104624,0.0,0.0,183.837615,2021-08-03,04:57:56.300000,1627966676,3.199
2,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446764,102.685593,28.069963,0.0,0.0,183.822042,2021-08-03,04:57:56.600002,1627966676,3.174
3,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446735,102.685591,28.067659,0.0,0.0,183.837356,2021-08-03,04:57:56.900000,1627966676,3.185
4,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446707,102.685590,28.068172,0.0,0.0,183.834719,2021-08-03,04:57:57.200002,1627966677,3.163

## Rename Columns

In [6]:
df.columns =['filename', 'latitude','longitude','height','roll','pitch','heading','date','time','unix_time_sec','distancetoprevious']
df

,filename,latitude,longitude,height,roll,pitch,heading,date,time,unix_time_sec,distancetoprevious
0,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446821,102.685597,28.148943,0.0,0.0,183.896560,2021-08-03,04:57:56.000180,1627966676,0.0
1,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446792,102.685595,28.104624,0.0,0.0,183.837615,2021-08-03,04:57:56.300000,1627966676,3.199
2,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446764,102.685593,28.069963,0.0,0.0,183.822042,2021-08-03,04:57:56.600002,1627966676,3.174
3,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446735,102.685591,28.067659,0.0,0.0,183.837356,2021-08-03,04:57:56.900000,1627966676,3.185
4,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446707,102.685590,28.068172,0.0,0.0,183.834719,2021-08-03,04:57:57.200002,1627966677,3.163
...,...,...,...,...,...,...,...,...,...,...,...
7156,2-0007-20210803-151352-000000075,2.441387,102.687680,29.541334,0.0,0.0,184.555140,2021-08-03,07:15:27.800002,1627974927,3.251
7157,2-0007-20210803-151352-000000076,2.441358,102.687678,29.551847,0.0,0.0,184.850068,2021-08-03,07:15:28.300001,1627974928,3.145
7158,2-0007-20210803-151352-000000077,2.441331,102.687676,29.610357,0.0,0.0,185.201085,2021-08-03,07:15:28.800002,1627974928,3.081
7159,2-0007-20210803-151352-000000078,2.441304,102.687673,29.642067,0.0,0.0,185.479538,2021-08-03,07:15:29.300000,1627974929,3.016
7160,2-0007-20210803-151352-000000079,2.441275,102.687670,29.685030,0.0,0.0,185.394953,2021-08-03,07:15:29.849995,1627974929,3.246

## Create new column named datetime

In [7]:
df['date'] = df['date'].str.split('-').str[0] + df['date'].str.split('-').str[1] + df['date'].str.split('-').str[2]
df['datetime'] = df['date']+ ' ' +  df['time']
df

,filename,latitude,longitude,height,roll,pitch,heading,date,time,unix_time_sec,distancetoprevious,datetime
0,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446821,102.685597,28.148943,0.0,0.0,183.896560,20210803,04:57:56.000180,1627966676,0.0,20210803 04:57:56.000180
1,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446792,102.685595,28.104624,0.0,0.0,183.837615,20210803,04:57:56.300000,1627966676,3.199,20210803 04:57:56.300000
2,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446764,102.685593,28.069963,0.0,0.0,183.822042,20210803,04:57:56.600002,1627966676,3.174,20210803 04:57:56.600002
3,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446735,102.685591,28.067659,0.0,0.0,183.837356,20210803,04:57:56.900000,1627966676,3.185,20210803 04:57:56.900000
4,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446707,102.685590,28.068172,0.0,0.0,183.834719,20210803,04:57:57.200002,1627966677,3.163,20210803 04:57:57.200002
...,...,...,...,...,...,...,...,...,...,...,...,...
7156,2-0007-20210803-151352-000000075,2.441387,102.687680,29.541334,0.0,0.0,184.555140,20210803,07:15:27.800002,1627974927,3.251,20210803 07:15:27.800002
7157,2-0007-20210803-151352-000000076,2.441358,102.687678,29.551847,0.0,0.0,184.850068,20210803,07:15:28.300001,1627974928,3.145,20210803 07:15:28.300001
7158,2-0007-20210803-151352-000000077,2.441331,102.687676,29.610357,0.0,0.0,185.201085,20210803,07:15:28.800002,1627974928,3.081,20210803 07:15:28.800002
7159,2-0007-20210803-151352-000000078,2.441304,102.687673,29.642067,0.0,0.0,185.479538,20210803,07:15:29.300000,1627974929,3.016,20210803 07:15:29.300000
7160,2-0007-20210803-151352-000000079,2.441275,102.687670,29.685030,0.0,0.0,185.394953,20210803,07:15:29.849995,1627974929,3.246,20210803 07:15:29.849995

## Datetime Format

In [8]:
import datetime
df['datetime'] = pd.to_datetime(df['datetime'], format='%Y%m%d %H:%M:%S')

In [17]:
df

,filename,latitude,longitude,height,roll,pitch,heading,date,time,unix_time_sec,distancetoprevious,datetime
0,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446821,102.685597,28.148943,0.0,0.0,183.896560,20210803,04:57:56.000180,1627966676,0.0,2021-08-03 04:57:56.000180
1,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446792,102.685595,28.104624,0.0,0.0,183.837615,20210803,04:57:56.300000,1627966676,3.199,2021-08-03 04:57:56.300000
2,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446764,102.685593,28.069963,0.0,0.0,183.822042,20210803,04:57:56.600002,1627966676,3.174,2021-08-03 04:57:56.600002
3,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446735,102.685591,28.067659,0.0,0.0,183.837356,20210803,04:57:56.900000,1627966676,3.185,2021-08-03 04:57:56.900000
4,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446707,102.685590,28.068172,0.0,0.0,183.834719,20210803,04:57:57.200002,1627966677,3.163,2021-08-03 04:57:57.200002
...,...,...,...,...,...,...,...,...,...,...,...,...
7156,2-0007-20210803-151352-000000075,2.441387,102.687680,29.541334,0.0,0.0,184.555140,20210803,07:15:27.800002,1627974927,3.251,2021-08-03 07:15:27.800002
7157,2-0007-20210803-151352-000000076,2.441358,102.687678,29.551847,0.0,0.0,184.850068,20210803,07:15:28.300001,1627974928,3.145,2021-08-03 07:15:28.300001
7158,2-0007-20210803-151352-000000077,2.441331,102.687676,29.610357,0.0,0.0,185.201085,20210803,07:15:28.800002,1627974928,3.081,2021-08-03 07:15:28.800002
7159,2-0007-20210803-151352-000000078,2.441304,102.687673,29.642067,0.0,0.0,185.479538,20210803,07:15:29.300000,1627974929,3.016,2021-08-03 07:15:29.300000
7160,2-0007-20210803-151352-000000079,2.441275,102.687670,29.685030,0.0,0.0,185.394953,20210803,07:15:29.849995,1627974929,3.246,2021-08-03 07:15:29.849995

## DateTime Index and convert to Asia/Singaport time

In [9]:
from datetime import datetime
from pytz import timezone
import pytz
format= 'H:%M:%S'
df.index = pd.to_datetime(df['datetime'], utc=True)
df.index = df.index.floor('S').tz_convert('Asia/Singapore')

In [10]:
df

,filename,latitude,longitude,height,roll,pitch,heading,date,time,unix_time_sec,distancetoprevious,datetime
datetime,,,,,,,,,,,,
2021-08-03 12:57:56+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446821,102.685597,28.148943,0.0,0.0,183.896560,20210803,04:57:56.000180,1627966676,0.0,2021-08-03 04:57:56.000180
2021-08-03 12:57:56+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446792,102.685595,28.104624,0.0,0.0,183.837615,20210803,04:57:56.300000,1627966676,3.199,2021-08-03 04:57:56.300000
2021-08-03 12:57:56+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446764,102.685593,28.069963,0.0,0.0,183.822042,20210803,04:57:56.600002,1627966676,3.174,2021-08-03 04:57:56.600002
2021-08-03 12:57:56+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446735,102.685591,28.067659,0.0,0.0,183.837356,20210803,04:57:56.900000,1627966676,3.185,2021-08-03 04:57:56.900000
2021-08-03 12:57:57+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446707,102.685590,28.068172,0.0,0.0,183.834719,20210803,04:57:57.200002,1627966677,3.163,2021-08-03 04:57:57.200002
...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-03 15:15:27+08:00,2-0007-20210803-151352-000000075,2.441387,102.687680,29.541334,0.0,0.0,184.555140,20210803,07:15:27.800002,1627974927,3.251,2021-08-03 07:15:27.800002
2021-08-03 15:15:28+08:00,2-0007-20210803-151352-000000076,2.441358,102.687678,29.551847,0.0,0.0,184.850068,20210803,07:15:28.300001,1627974928,3.145,2021-08-03 07:15:28.300001
2021-08-03 15:15:28+08:00,2-0007-20210803-151352-000000077,2.441331,102.687676,29.610357,0.0,0.0,185.201085,20210803,07:15:28.800002,1627974928,3.081,2021-08-03 07:15:28.800002
2021-08-03 15:15:29+08:00,2-0007-20210803-151352-000000078,2.441304,102.687673,29.642067,0.0,0.0,185.479538,20210803,07:15:29.300000,1627974929,3.016,2021-08-03 07:15:29.300000
2021-08-03 15:15:29+08:00,2-0007-20210803-151352-000000079,2.441275,102.687670,29.685030,0.0,0.0,185.394953,20210803,07:15:29.849995,1627974929,3.246,2021-08-03 07:15:29.849995

In [20]:
df['time'] = df.index.time
df['date'] = df.index.date
df

,filename,latitude,longitude,height,roll,pitch,heading,date,time,unix_time_sec,distancetoprevious,datetime
datetime,,,,,,,,,,,,
2021-08-03 12:57:56+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446821,102.685597,28.148943,0.0,0.0,183.896560,2021-08-03,12:57:56,1627966676,0.0,2021-08-03 04:57:56.000180
2021-08-03 12:57:56+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446792,102.685595,28.104624,0.0,0.0,183.837615,2021-08-03,12:57:56,1627966676,3.199,2021-08-03 04:57:56.300000
2021-08-03 12:57:56+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446764,102.685593,28.069963,0.0,0.0,183.822042,2021-08-03,12:57:56,1627966676,3.174,2021-08-03 04:57:56.600002
2021-08-03 12:57:56+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446735,102.685591,28.067659,0.0,0.0,183.837356,2021-08-03,12:57:56,1627966676,3.185,2021-08-03 04:57:56.900000
2021-08-03 12:57:57+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446707,102.685590,28.068172,0.0,0.0,183.834719,2021-08-03,12:57:57,1627966677,3.163,2021-08-03 04:57:57.200002
...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-03 15:15:27+08:00,2-0007-20210803-151352-000000075,2.441387,102.687680,29.541334,0.0,0.0,184.555140,2021-08-03,15:15:27,1627974927,3.251,2021-08-03 07:15:27.800002
2021-08-03 15:15:28+08:00,2-0007-20210803-151352-000000076,2.441358,102.687678,29.551847,0.0,0.0,184.850068,2021-08-03,15:15:28,1627974928,3.145,2021-08-03 07:15:28.300001
2021-08-03 15:15:28+08:00,2-0007-20210803-151352-000000077,2.441331,102.687676,29.610357,0.0,0.0,185.201085,2021-08-03,15:15:28,1627974928,3.081,2021-08-03 07:15:28.800002
2021-08-03 15:15:29+08:00,2-0007-20210803-151352-000000078,2.441304,102.687673,29.642067,0.0,0.0,185.479538,2021-08-03,15:15:29,1627974929,3.016,2021-08-03 07:15:29.300000
2021-08-03 15:15:29+08:00,2-0007-20210803-151352-000000079,2.441275,102.687670,29.685030,0.0,0.0,185.394953,2021-08-03,15:15:29,1627974929,3.246,2021-08-03 07:15:29.849995

## Remove datetime columns

In [21]:
df.drop(df.columns[[11]], axis=1, inplace=True)
df

,filename,latitude,longitude,height,roll,pitch,heading,date,time,unix_time_sec,distancetoprevious
datetime,,,,,,,,,,,
2021-08-03 12:57:56+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446821,102.685597,28.148943,0.0,0.0,183.896560,2021-08-03,12:57:56,1627966676,0.0
2021-08-03 12:57:56+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446792,102.685595,28.104624,0.0,0.0,183.837615,2021-08-03,12:57:56,1627966676,3.199
2021-08-03 12:57:56+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446764,102.685593,28.069963,0.0,0.0,183.822042,2021-08-03,12:57:56,1627966676,3.174
2021-08-03 12:57:56+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446735,102.685591,28.067659,0.0,0.0,183.837356,2021-08-03,12:57:56,1627966676,3.185
2021-08-03 12:57:57+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446707,102.685590,28.068172,0.0,0.0,183.834719,2021-08-03,12:57:57,1627966677,3.163
...,...,...,...,...,...,...,...,...,...,...,...
2021-08-03 15:15:27+08:00,2-0007-20210803-151352-000000075,2.441387,102.687680,29.541334,0.0,0.0,184.555140,2021-08-03,15:15:27,1627974927,3.251
2021-08-03 15:15:28+08:00,2-0007-20210803-151352-000000076,2.441358,102.687678,29.551847,0.0,0.0,184.850068,2021-08-03,15:15:28,1627974928,3.145
2021-08-03 15:15:28+08:00,2-0007-20210803-151352-000000077,2.441331,102.687676,29.610357,0.0,0.0,185.201085,2021-08-03,15:15:28,1627974928,3.081
2021-08-03 15:15:29+08:00,2-0007-20210803-151352-000000078,2.441304,102.687673,29.642067,0.0,0.0,185.479538,2021-08-03,15:15:29,1627974929,3.016
2021-08-03 15:15:29+08:00,2-0007-20210803-151352-000000079,2.441275,102.687670,29.685030,0.0,0.0,185.394953,2021-08-03,15:15:29,1627974929,3.246

In [23]:
#To check time converted correctly
df['time']

datetime
2021-08-03 12:57:56+08:00    12:57:56
2021-08-03 12:57:56+08:00    12:57:56
2021-08-03 12:57:56+08:00    12:57:56
2021-08-03 12:57:56+08:00    12:57:56
2021-08-03 12:57:57+08:00    12:57:57
                               ...
2021-08-03 15:15:27+08:00    15:15:27
2021-08-03 15:15:28+08:00    15:15:28
2021-08-03 15:15:28+08:00    15:15:28
2021-08-03 15:15:29+08:00    15:15:29
2021-08-03 15:15:29+08:00    15:15:29
Name: time, Length: 14322, dtype: object

In [24]:
df

,filename,latitude,longitude,height,roll,pitch,heading,date,time,unix_time_sec,distancetoprevious
datetime,,,,,,,,,,,
2021-08-03 12:57:56+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446821,102.685597,28.148943,0.0,0.0,183.896560,2021-08-03,12:57:56,1627966676,0.0
2021-08-03 12:57:56+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446792,102.685595,28.104624,0.0,0.0,183.837615,2021-08-03,12:57:56,1627966676,3.199
2021-08-03 12:57:56+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446764,102.685593,28.069963,0.0,0.0,183.822042,2021-08-03,12:57:56,1627966676,3.174
2021-08-03 12:57:56+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446735,102.685591,28.067659,0.0,0.0,183.837356,2021-08-03,12:57:56,1627966676,3.185
2021-08-03 12:57:57+08:00,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446707,102.685590,28.068172,0.0,0.0,183.834719,2021-08-03,12:57:57,1627966677,3.163
...,...,...,...,...,...,...,...,...,...,...,...
2021-08-03 15:15:27+08:00,2-0007-20210803-151352-000000075,2.441387,102.687680,29.541334,0.0,0.0,184.555140,2021-08-03,15:15:27,1627974927,3.251
2021-08-03 15:15:28+08:00,2-0007-20210803-151352-000000076,2.441358,102.687678,29.551847,0.0,0.0,184.850068,2021-08-03,15:15:28,1627974928,3.145
2021-08-03 15:15:28+08:00,2-0007-20210803-151352-000000077,2.441331,102.687676,29.610357,0.0,0.0,185.201085,2021-08-03,15:15:28,1627974928,3.081
2021-08-03 15:15:29+08:00,2-0007-20210803-151352-000000078,2.441304,102.687673,29.642067,0.0,0.0,185.479538,2021-08-03,15:15:29,1627974929,3.016
2021-08-03 15:15:29+08:00,2-0007-20210803-151352-000000079,2.441275,102.687670,29.685030,0.0,0.0,185.394953,2021-08-03,15:15:29,1627974929,3.246

## Reset datetime indexing

In [25]:
df.reset_index(drop=True, inplace=True)
df

,filename,latitude,longitude,height,roll,pitch,heading,date,time,unix_time_sec,distancetoprevious
0,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446821,102.685597,28.148943,0.0,0.0,183.896560,2021-08-03,12:57:56,1627966676,0.0
1,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446792,102.685595,28.104624,0.0,0.0,183.837615,2021-08-03,12:57:56,1627966676,3.199
2,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446764,102.685593,28.069963,0.0,0.0,183.822042,2021-08-03,12:57:56,1627966676,3.174
3,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446735,102.685591,28.067659,0.0,0.0,183.837356,2021-08-03,12:57:56,1627966676,3.185
4,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446707,102.685590,28.068172,0.0,0.0,183.834719,2021-08-03,12:57:57,1627966677,3.163
...,...,...,...,...,...,...,...,...,...,...,...
14317,2-0007-20210803-151352-000000075,2.441387,102.687680,29.541334,0.0,0.0,184.555140,2021-08-03,15:15:27,1627974927,3.251
14318,2-0007-20210803-151352-000000076,2.441358,102.687678,29.551847,0.0,0.0,184.850068,2021-08-03,15:15:28,1627974928,3.145
14319,2-0007-20210803-151352-000000077,2.441331,102.687676,29.610357,0.0,0.0,185.201085,2021-08-03,15:15:28,1627974928,3.081
14320,2-0007-20210803-151352-000000078,2.441304,102.687673,29.642067,0.0,0.0,185.479538,2021-08-03,15:15:29,1627974929,3.016
14321,2-0007-20210803-151352-000000079,2.441275,102.687670,29.685030,0.0,0.0,185.394953,2021-08-03,15:15:29,1627974929,3.246

## Check datatype

In [26]:
df.dtypes

filename               object
latitude              float64
longitude             float64
height                float64
roll                  float64
pitch                 float64
heading               float64
date                   object
time                   object
unix_time_sec           int64
distancetoprevious     object
dtype: object

In [207]:
df['time']

0       12:57:56.000180
1       12:57:56.300000
2       12:57:56.600002
3       12:57:56.900000
4       12:57:57.200002
             ...
7156    15:15:27.800002
7157    15:15:28.300001
7158    15:15:28.800002
7159    15:15:29.300000
7160    15:15:29.849995
Name: time, Length: 7161, dtype: object

In [28]:
df

,filename,latitude,longitude,height,roll,pitch,heading,date,time,unix_time_sec,distancetoprevious
0,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446821,102.685597,28.148943,0.0,0.0,183.896560,2021-08-03,12:57:56,1627966676,0.0
1,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446792,102.685595,28.104624,0.0,0.0,183.837615,2021-08-03,12:57:56,1627966676,3.199
2,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446764,102.685593,28.069963,0.0,0.0,183.822042,2021-08-03,12:57:56,1627966676,3.174
3,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446735,102.685591,28.067659,0.0,0.0,183.837356,2021-08-03,12:57:56,1627966676,3.185
4,2-0007-20210803-125707-2-0007-20210803-125707-...,2.446707,102.685590,28.068172,0.0,0.0,183.834719,2021-08-03,12:57:57,1627966677,3.163
...,...,...,...,...,...,...,...,...,...,...,...
14317,2-0007-20210803-151352-000000075,2.441387,102.687680,29.541334,0.0,0.0,184.555140,2021-08-03,15:15:27,1627974927,3.251
14318,2-0007-20210803-151352-000000076,2.441358,102.687678,29.551847,0.0,0.0,184.850068,2021-08-03,15:15:28,1627974928,3.145
14319,2-0007-20210803-151352-000000077,2.441331,102.687676,29.610357,0.0,0.0,185.201085,2021-08-03,15:15:28,1627974928,3.081
14320,2-0007-20210803-151352-000000078,2.441304,102.687673,29.642067,0.0,0.0,185.479538,2021-08-03,15:15:29,1627974929,3.016
14321,2-0007-20210803-151352-000000079,2.441275,102.687670,29.685030,0.0,0.0,185.394953,2021-08-03,15:15:29,1627974929,3.246